import { GoogleGenAI, Modality } from "@google/genai";

export const parseDataUrl = (dataUrl: string): { base64Data: string; mimeType: string } => {
  const parts = dataUrl.split(',');
  const mimeType = parts[0].match(/:(.*?);/)?.[1] || 'application/octet-stream';
  const base64Data = parts[1];
  return { base64Data, mimeType };
};

// Get API key from localStorage or environment variable
const getApiKey = (): string => {
  const storedKey = typeof window !== 'undefined' ? localStorage.getItem('gemini_api_key') : null;
  return storedKey || process.env.API_KEY || '';
};

export const editImage = async (base64Data: string, mimeType: string, prompt: string): Promise<string> => {
  const apiKey = getApiKey();
  if (!apiKey) {
    throw new Error('API key is not configured. Please add your Gemini API key in Settings.');
  }
  
  const ai = new GoogleGenAI({ apiKey });

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const restoredBase64 = part.inlineData.data;
        const restoredMimeType = part.inlineData.mimeType;
        return `data:${restoredMimeType};base64,${restoredBase64}`;
      }
    }

    throw new Error("No image was returned from the API.");
  } catch (error) {
    console.error("Error editing image:", error);
    if (error instanceof Error) {
      throw new Error(`Failed to communicate with the Gemini API: ${error.message}`);
    }
    throw new Error("An unknown error occurred while communicating with the Gemini API.");
  }
};

export const generateImage = async (prompt: string): Promise<string> => {
  const apiKey = getApiKey();
  if (!apiKey) {
    throw new Error('API key is not configured. Please add your Gemini API key in Settings.');
  }
  
  const ai = new GoogleGenAI({ apiKey });

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [{ text: prompt }],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const generatedBase64 = part.inlineData.data;
        const generatedMimeType = part.inlineData.mimeType;
        return `data:${generatedMimeType};base64,${generatedBase64}`;
      }
    }

    throw new Error("No image was generated by the API.");
  } catch (error) {
    console.error("Error generating image:", error);
    if (error instanceof Error) {
      throw new Error(`Failed to communicate with the Gemini API: ${error.message}`);
    }
    throw new Error("An unknown error occurred while communicating with the Gemini API.");
  }
};

export const generateVideo = async (prompt: string, image?: { base64Data: string; mimeType: string }): Promise<string> => {
  const apiKey = getApiKey();
  if (!apiKey) {
    throw new Error('API key is not configured. Please add your Gemini API key in Settings.');
  }
  
  const ai = new GoogleGenAI({ apiKey });

  const imagePayload = image ? {
    imageBytes: image.base64Data,
    mimeType: image.mimeType,
  } : undefined;

  try {
    let operation = await ai.models.generateVideos({
      model: 'veo-3.1-fast-generate-preview',
      prompt: prompt,
      ...(imagePayload && { image: imagePayload }),
      config: {
        numberOfVideos: 1,
        resolution: '720p',
        aspectRatio: '16:9'
      }
    });

    while (!operation.done) {
      await new Promise(resolve => setTimeout(resolve, 10000));
      operation = await ai.operations.getVideosOperation({ operation: operation });
    }

    const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
    if (!downloadLink) {
      throw new Error("Video generation completed, but no download link was provided.");
    }
    
    return downloadLink;
  } catch (error) {
    console.error("Error generating video:", error);
    if (error instanceof Error) {
      throw error;
    }
    throw new Error("An unknown error occurred while generating the video.");
  }
};
